"""add producer decisions

Revision ID: 3000b4d20390
Revises: ff8cd087e4de
Create Date: 2026-08-11 03:25:43.325592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3000b4d20390'
down_revision = 'ff8cd087e4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producer_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_department', sa.String(length=100), nullable=True),
    sa.Column('assigned_person', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_producer_decisions_document_id_documents')),
    sa.ForeignKeyConstraint(['observation_id'], ['producer_observations.id'], name=op.f('fk_producer_decisions_observation_id_producer_observations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producer_decisions'))
    )
    op.create_index(op.f('ix_producer_decisions_id'), 'producer_decisions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_producer_decisions_id'), table_name='producer_decisions')
    op.drop_table('producer_decisions')
    # ### end Alembic commands ###
