"""expand extraction fields

Revision ID: 339a7a751b55
Revises: 536298428149
Create Date: 2026-08-09 12:20:58.209769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '339a7a751b55'
down_revision = '536298428149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('characters', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('occupation', sa.String(length=255), nullable=False))
    op.add_column('characters', sa.Column('scenes', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('locations', sa.Column('scenes', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('props', sa.Column('scenes', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('scenes', sa.Column('characters', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('scenes', sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'props')
    op.drop_column('scenes', 'characters')
    op.drop_column('props', 'scenes')
    op.drop_column('locations', 'scenes')
    op.drop_column('characters', 'scenes')
    op.drop_column('characters', 'occupation')
    op.drop_column('characters', 'age')
    op.drop_column('characters', 'aliases')
    # ### end Alembic commands ###
