"""add decision status to producer observations

Revision ID: 4a5fc7b59e95
Revises: 56b1c7e94e81
Create Date: 2026-08-17 04:01:18.019576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5fc7b59e95'
down_revision = '56b1c7e94e81'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "producer_observations",
        sa.Column(
            "decision_status",
            sa.String(length=30),
            nullable=False,
            server_default="pending",
        ),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producer_observations', 'decision_status')
    # ### end Alembic commands ###
