"""add production tasks

Revision ID: 507d059b75da
Revises: 3000b4d20390
Create Date: 2026-08-12 01:28:47.836618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507d059b75da'
down_revision = '3000b4d20390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('assigned_person', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['producer_decisions.id'], name=op.f('fk_production_tasks_decision_id_producer_decisions')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_production_tasks_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_tasks'))
    )
    op.create_index(op.f('ix_production_tasks_id'), 'production_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_tasks_id'), table_name='production_tasks')
    op.drop_table('production_tasks')
    # ### end Alembic commands ###
