"""add production tasks

Revision ID: 56b1c7e94e81
Revises: 507d059b75da
Create Date: 2026-08-12 01:30:40.160835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b1c7e94e81'
down_revision = '507d059b75da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
