"""add producer observations

Revision ID: ff8cd087e4de
Revises: 339a7a751b55
Create Date: 2026-08-11 00:47:02.102710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8cd087e4de'
down_revision = '339a7a751b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producer_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('basis_type', sa.String(length=20), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('requires_human_decision', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_producer_observations_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producer_observations'))
    )
    op.create_index(op.f('ix_producer_observations_id'), 'producer_observations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_producer_observations_id'), table_name='producer_observations')
    op.drop_table('producer_observations')
    # ### end Alembic commands ###
